### ISSUE TITLE
Can not build d8 on Windows 11

### ISSUE THREAD

**Issue by CGQAQ** [bnoordhuis/v8-cmake#73] opened 2023-07-19 00:59 UTC
[Build output](https://pastebin.ubuntu.com/p/F6YxQsWbzy/)

Seems like generating from tq file is failed

**Comment by bnoordhuis** [comment] 2023-07-19 07:47
Probably a duplicate of #67. Possibly caused by the command line arguments being too long for Windows to handle.

**Comment by CGQAQ** [comment] 2023-07-19 09:21
build `array-at.tq` and it's `deps` works

<details><summary>Details</summary>
<p>

PS D:\tmp\torque> .\torque.exe -o d:\tmp\torque\torque-generated -v8-root d:\tmp\v8-cmake\v8 src/builtins/array-at.tq src/builtins/number.tq src/builtins/base.tq src/objects/heap-object.tq src/objects/name.tq src/objects/primitive-heap-object.tq src/objects/string.tq src/objects/oddball.tq src/objects/bigint.tq src/objects/heap-number.tq src/objects/js-objects.tq src/objects/fixed-array.tq src/objects/foreign.tq src/objects/js-proxy.tq src/objects/js-function.tq src/wasm/wasm-objects.tq src/objects/contexts.tq src/objects/js-weak-refs.tq src/objects/map.tq src/objects/struct.tq src/objects/scope-info.tq src/builtins/torque-internal.tq src/objects/regexp-match-info.tq src/objects/shared-function-info.tq src/builtins/convert.tq src/builtins/cast.tq src/objects/feedback-vector.tq src/objects/js-array.tq src/objects/swiss-name-dictionary.tq src/objects/js-array-buffer.tq src/objects/property-array.tq src/objects/prototype-info.tq src/builtins/string-trim.tq src/objects/js-regexp.tq src/objects/arguments.tq src/builtins/frame-arguments.tq src/builtins/frames.tq src/objects/promise.tq src/objects/microtask.tq src/objects/swiss-hash-table-helpers.tq src/objects/source-text-module.tq src/objects/module.tq src/objects/feedback-cell.tq src/objects/bytecode-array.tq src/objects/descriptor-array.tq src/objects/api-callbacks.tq src/objects/cell.tq src/objects/script.tq src/builtins/iterator.tq src/objects/debug-objects.tq src/objects/js-promise.tq src/objects/js-generator.tq
src/builtins/number.tq:74:28: Torque Error: cannot find "math::Word32Clz"
src/builtins/number.tq:73:7: Lint error: Variable 'n' is never assigned to. Use 'const' instead of 'let'.
src/builtins/number.tq:70:15: Lint error: Variable 'log10OffsetsTable' is never used. Prefix with '_' if this is intentional.
src/builtins/number.tq:293:21: Torque Error: cannot find "string::ToString"
src/builtins/number.tq:334:35: Torque Error: cannot find "math::Float64Abs"
src/builtins/number.tq:333:15: Lint error: Variable 'kMaxAbsValue' is never used. Prefix with '_' if this is intentional.
src/builtins/number.tq:347:11: Lint error: Label 'String' is never used. Prefix with '_' if this is intentional.
src/builtins/number.tq:406:22: Torque Error: cannot find "math::TrySmiAdd"
src/builtins/number.tq:485:11: Lint error: Label 'StringAddConvertLeft' is never used. Prefix with '_' if this is intentional.
src/builtins/number.tq:487:11: Lint error: Label 'StringAddConvertRight' is never used. Prefix with '_' if this is intentional.
src/builtins/number.tq:489:11: Lint error: Label 'Numerics' is never used. Prefix with '_' if this is intentional.
src/builtins/number.tq:491:11: Lint error: Label 'Float64s' is never used. Prefix with '_' if this is intentional.
src/builtins/number.tq:398:7: Lint error: Variable 'left' is never assigned to. Use 'const' instead of 'let'.
src/builtins/number.tq:399:7: Lint error: Variable 'right' is never assigned to. Use 'const' instead of 'let'.
src/builtins/number.tq:651:14: Torque Error: cannot find "math::TrySmiSub"
src/builtins/number.tq:672:5: Torque Error: cannot find "bigint::BigIntMultiply"
src/builtins/number.tq:711:5: Torque Error: cannot find "bigint::BigIntDivide"
src/builtins/number.tq:723:5: Torque Error: cannot find "bigint::BigIntModulus"
src/builtins/number.tq:732:12: Torque Error: cannot find "math::MathPowImpl"
src/builtins/number.tq:815:5: Torque Error: cannot find "bigint::BigIntBitwiseAnd"
src/builtins/number.tq:828:5: Torque Error: cannot find "bigint::BigIntBitwiseOr"
src/builtins/number.tq:841:5: Torque Error: cannot find "bigint::BigIntBitwiseXor"
src/builtins/base.tq:647:17: Torque Error: cannot find "math::Float64Trunc"
src/builtins/base.tq:645:13: Lint error: Variable 'value' is never assigned to. Use 'const' instead of 'let'.
src/builtins/base.tq:637:7: Lint error: Variable 'input' is never assigned to. Use 'const' instead of 'let'.
src/builtins/base.tq:1896:7: Torque Error: cannot find "array::EnsureWriteableFastElements"
src/builtins/base.tq:1895:13: Lint error: Variable 'kind' is never used. Prefix with '_' if this is intentional.
src/builtins/base.tq:1886:39: Lint error: Variable 'value' is never used. Prefix with '_' if this is intentional.
src/objects/bigint.tq:17:10: Torque Error: cannot find "bigint::IsCanonicalized"
src/builtins/cast.tq:24:10: Torque Error: cannot find "AllocationSite"
src/builtins/cast.tq:23:24: Lint error: Variable 'o' is never used. Prefix with '_' if this is intentional.
src/builtins/cast.tq:458:7: Torque Error: cannot find "regexp::IsRegExpResult"
src/builtins/cast.tq:457:12: Lint error: Label 'CastError' is never used. Prefix with '_' if this is intentional.
src/builtins/cast.tq:503:7: Torque Error: cannot find "regexp::IsFastRegExpStrict"
src/builtins/cast.tq:498:12: Lint error: Label 'CastError' is never used. Prefix with '_' if this is intentional.
src/builtins/iterator.tq:109:3: Torque Error: cannot find "ic::CollectCallFeedback"
src/objects/js-array.tq:266:5: Torque Error: cannot find "array::EnsureWriteableFastElements"
src/builtins/string-trim.tq:133:10: Torque Error: cannot find "SubString"
src/builtins/string-trim.tq:144:12: Torque Error: Note: in specialization StringTrimBody<char8> requested here
src/builtins/string-trim.tq:133:10: Torque Error: cannot find "SubString"
src/builtins/string-trim.tq:146:12: Torque Error: Note: in specialization StringTrimBody<char16> requested here
src/builtins/number.tq:384:21: Lint error: Macro 'ToNumericOrPrimitive' is never used.
src/builtins/base.tq:785:21: Lint error: Macro 'ToPrimitiveDefault' is never used.
src/builtins/base.tq:859:21: Lint error: Macro 'ElementsKindNotEqual' is never used.
src/builtins/base.tq:919:21: Lint error: Macro 'IsNumberNotEqual' is never used.
src/builtins/base.tq:1122:7: Lint error: Macro 'Min' is never used.
src/builtins/base.tq:1125:7: Lint error: Macro 'Max' is never used.
src/builtins/base.tq:1164:34: Lint error: Macro 'LoadJSArrayLengthAsUintPtr' is never used.
src/builtins/base.tq:1170:34: Lint error: Macro 'LoadStringLengthAsUintPtr' is never used.
src/builtins/base.tq:1178:20: Lint error: Macro 'StringAdd' is never used.
src/builtins/base.tq:1266:7: Lint error: Macro 'Int32Constant' is never used.
src/builtins/base.tq:1286:7: Lint error: Macro 'IntPtrConstant' is never used.
src/builtins/base.tq:1366:7: Lint error: Macro 'FastHoleyElementsKind' is never used.
src/builtins/base.tq:1376:7: Lint error: Macro 'AllowDoubleElements' is never used.
src/builtins/base.tq:1385:7: Lint error: Macro 'AllowNonNumberElements' is never used.
src/builtins/base.tq:1401:7: Lint error: Macro 'GetArrayFunction' is never used.
src/builtins/base.tq:1404:7: Lint error: Macro 'GetArrayBufferFunction' is never used.
src/builtins/base.tq:1407:7: Lint error: Macro 'GetArrayBufferNoInitFunction' is never used.
src/builtins/base.tq:1410:7: Lint error: Macro 'GetIteratorFunction' is never used.
src/builtins/base.tq:1423:7: Lint error: Macro 'GetIteratorResultMap' is never used.
src/builtins/base.tq:1426:7: Lint error: Macro 'GetInitialStringIteratorMap' is never used.
src/builtins/base.tq:1429:7: Lint error: Macro 'GetReflectApply' is never used.
src/builtins/base.tq:1432:7: Lint error: Macro 'GetRegExpLastMatchInfo' is never used.
src/builtins/base.tq:1444:7: Lint error: Macro 'GetWeakCellMap' is never used.
src/builtins/base.tq:1447:7: Lint error: Macro 'GetPrototypeApplyFunction' is never used.
src/builtins/base.tq:1496:7: Lint error: Macro 'ToBoolean' is never used.
src/builtins/base.tq:1513:7: Lint error: Macro 'SameValue' is never used.
src/builtins/base.tq:1533:7: Lint error: Macro 'CheckIntegerIndexAdditionOverflow' is never used.
src/builtins/base.tq:1633:21: Lint error: Macro 'ToUintPtr' is never used.
src/builtins/base.tq:1699:21: Lint error: Macro 'GetMethod' is never used.
src/builtins/base.tq:1704:21: Lint error: Macro 'GetMethod' is never used.
src/builtins/base.tq:1951:7: Lint error: Macro 'IsIntegerOrSomeInfinity' is never used.
src/builtins/base.tq:1968:7: Lint error: Macro 'NumberIsSomeInfinity' is never used.
src/builtins/base.tq:2002:7: Lint error: Macro 'ReplaceTheHoleWithUndefined' is never used.
src/objects/string.tq:346:7: Lint error: Macro 'StaticAssertStringLengthFitsSmi' is never used.
src/objects/js-objects.tq:36:7: Lint error: Macro 'NewJSObject' is never used.
src/objects/js-objects.tq:82:7: Lint error: Macro 'GetDerivedRabGsabTypedArrayMap' is never used.
src/objects/fixed-array.tq:90:22: Lint error: Macro 'StoreFixedDoubleArrayDirect' is never used.
src/objects/fixed-array.tq:94:22: Lint error: Macro 'StoreFixedArrayDirect' is never used.
src/objects/fixed-array.tq:123:7: Lint error: Macro 'ExtractFixedArray' is never used.
src/objects/fixed-array.tq:133:7: Lint error: Macro 'ExtractFixedDoubleArray' is never used.
src/objects/js-proxy.tq:15:7: Lint error: Macro 'NewJSProxyRevocableResult' is never used.
src/objects/js-array.tq:98:7: Lint error: Macro 'NewJSArrayFilledWithZero' is never used.
src/objects/js-array.tq:199:7: Lint error: Macro 'TorqueCopyElements' is never used.
src/objects/js-array.tq:206:7: Lint error: Macro 'TorqueCopyElements' is never used.
src/objects/js-array.tq:319:7: Lint error: Macro 'NewFastJSArrayWitness' is never used.
src/objects/js-array.tq:366:7: Lint error: Macro 'NewFastJSArrayForReadWitness' is never used.
src/objects/js-array-buffer.tq:98:7: Lint error: Macro 'LoadJSArrayBufferViewByteLength' is never used.
src/builtins/frames.tq:62:26: Lint error: Macro 'LoadCallerFromFrame' is never used.
src/builtins/frames.tq:103:21: Lint error: Macro 'FrameTypeEquals' is never used.
src/objects/string.tq:15:9: Lint error: Macro 'IsNotInternalized' is never used.
src/objects/string.tq:20:9: Lint error: Macro 'IsOneByteRepresentation' is never used.
src/objects/string.tq:32:9: Lint error: Macro 'IsOneByteRepresentationUnderneath' is never used.
src/builtins/base.tq:167:9: Lint error: Macro 'ValueUnsafeAssumeNotHole' is never used.
src/objects/map.tq:55:9: Lint error: Macro 'IsUndetectable' is never used.
src/objects/regexp-match-info.tq:8:9: Lint error: Macro 'GetStartOfCapture' is never used.
src/objects/regexp-match-info.tq:13:9: Lint error: Macro 'GetEndOfCapture' is never used.
src/objects/regexp-match-info.tq:18:9: Lint error: Macro 'NumberOfCaptures' is never used.
src/objects/js-array.tq:61:9: Lint error: Macro 'IsEmpty' is never used.
src/objects/js-array.tq:217:9: Lint error: Macro 'Get' is never used.
src/objects/js-array.tq:221:9: Lint error: Macro 'Recheck' is never used.
src/objects/js-array.tq:244:9: Lint error: Macro 'StoreHole' is never used.
src/objects/js-array.tq:256:9: Lint error: Macro 'LoadElementOrUndefined' is never used.
src/objects/js-array.tq:264:9: Lint error: Macro 'EnsureArrayPushable' is never used.
src/objects/js-array.tq:270:9: Lint error: Macro 'ChangeLength' is never used.
src/objects/js-array.tq:275:9: Lint error: Macro 'Push' is never used.
src/objects/js-array.tq:293:9: Lint error: Macro 'MoveElements' is never used.
src/objects/js-array.tq:333:9: Lint error: Macro 'Get' is never used.
src/objects/js-array.tq:337:9: Lint error: Macro 'Recheck' is never used.
src/objects/js-array.tq:349:9: Lint error: Macro 'LoadElementNoHole' is never used.
src/objects/js-promise.tq:18:9: Lint error: Macro 'SetStatus' is never used.
src/objects/js-promise.tq:25:9: Lint error: Macro 'HasHandler' is never used.
src/objects/js-promise.tq:29:9: Lint error: Macro 'SetHasHandler' is never used.

</p>
</details>

**Comment by bnoordhuis** [comment] 2023-07-19 09:43
Yeah, that's more or less what I expect. You can maybe stay just below the threshold when you move your project from D:/tmp/v8-cmake to e.g. D:/v8. Putting cmake.exe in the root of C: or D: may help as well.

Replacing `torque-generated` with e.g. `tq` in CMakeLists.txt is probably a good idea too. If that fixes the long path issue for you, I'll consider making that change in the repo.

**Comment by CGQAQ** [comment] 2023-07-20 00:31
I'll try to make a PR fix this :)

**Closed** 2024-01-04 06:23 UTC
