### ISSUE TITLE
v8-i18n-support issue

### ISSUE THREAD

**Issue by hejian1639** [bnoordhuis/v8-cmake#39] opened 2020-10-27 04:47 UTC
```
You have called ADD_LIBRARY for library v8-i18n-support without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at CMakeLists.txt:154 (target_link_libraries):
  Object library target "v8-i18n-support" may not link to anything.
```

I got this issue on ubuntu 18 , when cmake runs, it works on my MacBook

**Comment by bnoordhuis** [comment] 2020-10-27 07:54
Are you passing `-DV8_ENABLE_I18N=ON` to cmake? i18n builds aren't working yet, pending resolution of #4.

**Comment by hejian1639** [comment] 2020-10-28 01:38
```
cmake -DCMAKE_BUILD_TYPE=Debug 
```
above is my arguments and I tried -DV8_ENABLE_I18N=ON/OFF both, still same result ...

**Comment by bnoordhuis** [comment] 2020-10-28 08:01
I'm afraid I can't reproduce. My best guess it's a cmake incompatibility. I'm testing with cmake 3.16.3.

**Comment by hejian1639** [comment] 2020-11-09 03:43
yes, I guess so , I use latest cmake , it works now. 
thank u.

**Comment by bnoordhuis** [comment] 2020-11-09 12:50
Glad to hear it's working now. I'll close the issue.

**Closed by bnoordhuis** 2020-11-09 12:50 UTC
